site_name: geshu-compendium
theme:
  name: material
plugins:
  - search
nav:
  - Notes:
      - Data Structure: courses/cs61b/index.md
      - Efficient Algorithm: courses/cs170/index.md
      - Networks: courses/cs194/index.md
      - Algorithms in Real World Application: courses/cmu-15-850c/index.md
  - Resources: resources/index.md
  - Blog: blog/index.md
markdown_extensions:
  - toc:
      permalink: true
